CREATE USER 'INSERT_YOUR_USERNAME'@'localhost' IDENTIFIED BY 'INSERT_YOUR_PASSWORD';

GRANT INSERT, SELECT, UPDATE, DELETE ON visa_world_cup.* TO 'INSERT_YOUR_USERNAME'@'localhost';

FLUSH PRIVILEGES;